client
dev tun
proto udp
remote 177.153.69.11 1194
resolv-retry infinite
nobind
persist-key
persist-tun
ca /etc/openvpn/client/ca.crt
cert /etc/openvpn/client/dev.appvitae.paynboxapp.com.crt
key /etc/openvpn/client/dev.appvitae.paynboxapp.com.key
tls-auth /etc/openvpn/client/ta.key 1
verb 3
data-ciphers AES-256-GCM
data-ciphers-fallback AES-256-CBC
remote-cert-tls server
tun-mtu 1500